# this  YAML file will allow me to store configuration variables
# and to be able to run different environments dynamically
DEVELOP:
  BASE_URL: https://dev.general-dynamics.com
  ADMIN_USERNAME: test@hotmail.com
  ADMIN_PASSWORD: testing123

PREPROD:
  BASE_URL: https://preprod.general-dynamics.com
  ADMIN_USERNAME: test@hotmail.com
  ADMIN_PASSWORD: testing123

PROD:
  BASE_URL: https://general-dynamics.com
  ADMIN_USERNAME: test@hotmail.com
  ADMIN_PASSWORD: testing123
