# config.yaml
DEVELOP:
  base_url:
  database_url: dev_database_url
  secret_key: dev_secret_key

PREPROD:
  base_url:
  database_url: staging_database_url
  secret_key: staging_secret_key

PROD:
  BASE_URL: https://facebook.com
  USERNAME: matias.perichon@hotmail.com
  PASSWORD: matiasp1998
